services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo

  reservations:
    image: 'boconlonton/sleepr:reservations-production'
    env_file: ../apps/reservations/.env
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  auth:
    image: 'boconlonton/sleepr:auth-production'
    env_file: ../apps/auth/.env
    ports:
      - '3001:3001'
    depends_on:
      - mongo

  payments:
    image: 'boconlonton/sleepr:payments-production'
    env_file: ../apps/payments/.env
    depends_on:
      - mongo

  notifications:
    image: 'boconlonton/sleepr:notifications-production'
    env_file: ../apps/notifications/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: sleepr
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

volumes:
  db:
